[package]
name = "kipi"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio = { version = "1.38.0", features = ["full"] }
sqlx = { version = "0.7.4", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }

rpassword = "7.3"
